language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: seanpue
  password:
    secure: RD7hk28ErRvgryfH+hP6z2eNSrn2IkU9FG4+hMRf/amCxphJ61hWeMGFRF9Z1/lMQvNJwEBgMTwsWLsqcH62F3pJUIx3ry45Q9UMipn7cZ1LNN4M6Vz8vBCNOclZ99yagdDVT8hBVaAOa6TQLvGY2pvrPBQeXWt+ynDkemdd86Qk2q1qHIYUrOHGu32X6VsG6ocZsZmpecLK7OC3fnlL+jXN5VL6vYMCJl3BipDz7vlN4iCCPv/AJMf9jOQvE82Bbt8JUPDkGV7bzVaicAeVQC7Bn0Ggy9jLxZjeygUGCm1cib7lw3RVspexuf3sKgnAUNGkWrOfO71VjZaTYH1aaf5VyJLXZmuEJbgFZ2ChHr2h1LMCYT6pUkN7Hfi7Be7cNwC0kwjd2jfFdjEXedPPippDgdHXsZTj0ikGrZaHYOkeFNuSIQcMITjCxzYpj6ZjTR21cBoAgWLRKJEicKhjN8N2sSh0uewn2GuoleCLPv67hNeqXz9nuriMGy4CecOJonZn6Updm3w1JYzzWuGPnCvCrKgfOjXB/UZk1+hF0tIuifDlSsN/g25Z86S4e+N9siHhZGO9Ku0v6F5Z7J1+D9+19h4mCg7Lu27ZgA3r/KghFzgMosfDu74BNg/gFtnUYQ/bMk7NTyPDAmpfqFk/CQVTR+NMm2gL95oS+Rgc3Gk=
  on:
    tags: true
    repo: seanpue/urdubiometer
    python: 3.6
