#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Script to generate translated messages.

Adapted from Nikola, a static site generator (c) 2019 Roberto Alsina and others,
MIT License.

https://github.com/getnikola/nikola/blob/7961ae2395ba4ecccf4f6fa3715f92dfed04d50e/scripts/import_po.py

"""
from glob import glob
import os
import pprint
import sys
import polib

# changed nopull to pull
if "pull" in sys.argv or "--pull" in sys.argv:
    os.system("tx pull -a")
elif "-h" in sys.argv or "--help" in sys.argv:
    print("Internal use only. Takes optional 'pull' argument to pull from Transifex.")
    exit()

trans_files = glob(os.path.join("translations", "urdubiometer.messages", "*.po"))

messages = {}

for fname in trans_files:
    lang = os.path.splitext(os.path.basename(fname))[0].lower()
    assert lang != "en-new", "Remnant from scripts/extract_strings.py"
    lang = lang.replace("@", "_")
    messages[lang] = {}
    # not data/themes/base/messages but data/messages
    po = polib.pofile(fname)

    for entry in po:
        messages[lang][entry.msgid] = entry.msgstr

base_lang = "en"

for lang in messages.keys():
    if lang == base_lang:
        continue
    for key, value in messages[base_lang].items():
        if key not in messages[lang]:
            messages[lang][key] = value
lines = (
    "# -*- encoding:utf-8 -*-\n"
    + "# Autogenerated file, do not edit. Submit translations on Transifex.\n"
    + "\n"
    + "MESSAGES = {\n "
    + pprint.pformat(messages, width=88, indent=1)[1:]
    + "\n"
)

with open("urdubiometer/data/messages.py", "w") as f:
    f.write(lines)
# pprint.pformat(messages, indent=4)

#
# lines.extend(sorted(lines2))
# lines.append("}\n")
# print("Generating:", outf)
# with io.open(outf, "w+", encoding="utf8") as outfile:
#     outfile.write("\n".join(lines))
